### ISSUE TITLE
missing "filesystem" in final ignition config

### ISSUE THREAD

**Issue by mrguitar** [ashcrow/filetranspiler#1]
Amazing work on this!

A simple file rendered with filetranspiler will look like this:
    "storage": {
        "files": [
            {
                "contents": {
                    "source": "data:,search%20example.com%0Anameserver%208.8.8.8%0Anameserver%204.4.4.4%0A"
                },
                "mode": 420,
                "path": "/etc/resov.conf"
            },

my system will complain about requiring the "filesystem" directive. Inserting '"filesystem": "root",' seems to fix the issue, but I'm unsure if this should be configurable in this app, or if it should default to the "root" fs.

    "storage": {
        "files": [
            {
                "contents": {
                    "source": "data:,search%20example.com%0Anameserver%208.8.8.8%0Anameserver%204.4.4.4%0A"
                },
                "filesystem": "root",
                "mode": 420,
                "path": "/etc/resov.conf"
            },

**Comment by ashcrow** [comment]
```
$ ./filetranspile -i ignition.json -f fakeroot
<snip/>
            {
                "contents": {
                    "source": "data:,blah%20blah%20blah%0A1234567890%0Ablah%20blah%20blah%0A"
                },
                "filesystem": "root",
                "mode": 436,
                "path": "/etc/sysconfig/work-scripts/ifcfg-blah"
            }
<snip/>
```
