### ISSUE TITLE
RPM package

### ISSUE THREAD

**Issue by e-minguez** [ashcrow/filetranspiler#14]
Just FYI, I've added the filetranspiler RPM package to my copr repo https://copr.fedorainfracloud.org/coprs/eminguez/eminguez-RPMs/package/filetranspiler/

**Comment by ashcrow** [comment]
Nice! Do you foresee any want to have it part of Fedora, etc..?

**Comment by e-minguez** [comment]
I'm not sure TBH. The spec is a quick and dirty one so it won't pass the Fedora guidelines :D I just did it for myself to be able to quickly install it for some tests. If there is some interest I can improve it and send it to Fedora validation if you want.

**Comment by ashcrow** [comment]
Given that [`fcct`](https://github.com/coreos/fcct/) is expected to replace `filetranspiler` over time I'm going to close this issue.
