### ISSUE TITLE
SyntaxError line 135: f'link: {source_path} is not in the '

### ISSUE THREAD

**Issue by psergiu** [ashcrow/filetranspiler#16]
Getting a syntax error when trying to update a OpenShift bootstrap ignition file as described in: https://blog.openshift.com/openshift-4-bare-metal-install-quickstart/
```

$ ls -l
total 308
drwxr-x--- 2 psergiu psergiu   4096 Feb 18 10:08 auth
drwxr-xr-x 3 psergiu psergiu   4096 Feb 17 14:25 bootstrap
-rw-r----- 1 psergiu psergiu 292125 Feb 18 10:08 bootstrap.ign
-rw-r----- 1 psergiu psergiu   1833 Feb 18 10:08 master.ign
-rw-r----- 1 psergiu psergiu    104 Feb 18 10:08 metadata.json
-rw-r----- 1 psergiu psergiu   1833 Feb 18 10:08 worker.ign

$ tree bootstrap
bootstrap
└── etc
    ├── hostname
    ├── resolv.conf
    └── sysconfig
        └── network-scripts
            └── ifcfg-ens192

3 directories, 3 files

$ python3 ~/Downloads/filetranspiler-master/filetranspile -i bootstrap.ign -f bootstrap -o bootstrap-static.ign
  File "/home/psergiu/Downloads/filetranspiler-master/filetranspile", line 135
    f'link: {source_path} is not in the '
                                        ^
SyntaxError: invalid syntax

$ python2 ~/Downloads/filetranspiler-master/filetranspile -i bootstrap.ign -f bootstrap -o bootstrap-static.ign
  File "/home/psergiu/Downloads/filetranspiler-master/filetranspile", line 135
    f'link: {source_path} is not in the '
                                        ^
SyntaxError: invalid syntax

```

**Comment by ashcrow** [comment]
Thanks for the report! I'll look into it.

**Comment by ashcrow** [comment]
So far I am not able to reproduce this with `python3`. However, `python2` does indeed throw a SyntaxError using the [f-strings](https://www.python.org/dev/peps/pep-0498/).

The python3 version I'm testing with is Python 3.7.6. From the above link on f-strings it looks like that feature was added in Python 3.6. Can you provide what Python 3 version you hit this error with?

With that said, it may be worth removing the f-string usage as some folks may not be able to upgrade their Python when their system has something _before_ Python 3.6.0.

**Comment by ashcrow** [comment]
Opened https://github.com/ashcrow/filetranspiler/pull/17 which removes f-string usage and replaces it with `'..{}..'.format(..)`. This should allow older Python 3 installs to pass.

**Comment by ashcrow** [comment]
I've tagged [v1.1.1](https://github.com/ashcrow/filetranspiler/releases/tag/1.1.1) which includes the removal of f-strings. Please re-open this if the issue persists _or_ open a new issue if you run into another problem.

**Comment by psergiu** [comment]
Thanks a lot !
This happened on a Debian 9 "oldstable" box with it's default python 3.5
```
$ python3 --version
Python 3.5.3
```
The error is no more, seems to be working now. Thank you !
