### ISSUE TITLE
Update README with dependencies

### ISSUE THREAD

**Issue by psergiu** [ashcrow/filetranspiler#18]
Please add in the README file that the python script requires python3-yaml to be installed ( not installed by default on Debian )
```
$ python3 ~/Downloads/filetranspiler-master/filetranspile -i bootstrap.ign -f bootstrap -o bootstrap-static.ign
Traceback (most recent call last):
  File "/home/psergiu/Downloads/filetranspiler-master/filetranspile", line 12, in <module>
    import yaml
ImportError: No module named 'yaml'
```
Thank you !

**Comment by ashcrow** [comment]
PTAL at #19 and let me know if that looks like it would clarify properly. I didn't denote specific packages, but did denote recommended Python version as well as the library itself.

**Comment by psergiu** [comment]
Looks perfect ! Thank you very much.
