### ISSUE TITLE
base64 encoded output

### ISSUE THREAD

**Issue by lbohnsac** [ashcrow/filetranspiler#20]
A command line switch to have base64 encoded utf-8 output would be perfect!
Me python skills are very limited ... i tried to modify your code but the result looks not as expected ... :(

**Comment by ashcrow** [comment]
@lbohnsac in terms of output do you mean on encoding files within the Ignition configuration _or_ encoding the literal output of the file for a use case?

**Comment by lbohnsac** [comment]
I modified with my basic skills your script in that way:
diff filetranspile filetranspile.base64
13d12
< import base64
179,181d177
<         file_contents_bytes = file_contents.encode('ascii')
<         file_contents_base64 = base64.b64encode(file_contents_bytes)
<         file_contents = file_contents_base64.decode('ascii')
187c183
<                 'source': 'data:text/plain;charset=utf-8;base64,{}'.format(file_contents)
---
>                 'source': 'data:,{}'.format(quote(file_contents))
228,231d223
<         file_contents_bytes = file_contents.encode('ascii')
<         file_contents_base64 = base64.b64encode(file_contents_bytes)
<         file_contents = file_contents_base64.decode('ascii')
< 
237c229
<                 'source': 'data:text/plain;charset=utf-8;base64,{}'.format(file_contents)
---
>                 'source': 'data:,{}'.format(quote(file_contents))
326c318
< 
---
> 

Maybe you can add a cmd switch base64 output yes/no like -64

**Comment by lbohnsac** [comment]
Something like this but with a command line switch like -64:
```
diff filetranspile filetranspile.base64
13d12
< import base64
179,181d177
<         file_contents_bytes = file_contents.encode('utf-8')
<         file_contents_base64 = base64.b64encode(file_contents_bytes)
<         file_contents = file_contents_base64.decode('utf-8')
187c183
<                 'source': 'data:text/plain;charset=utf-8;base64,{}'.format(file_contents)
---
>                 'source': 'data:,{}'.format(quote(file_contents))
228,231d223
<         file_contents_bytes = file_contents.encode('utf-8')
<         file_contents_base64 = base64.b64encode(file_contents_bytes)
<         file_contents = file_contents_base64.decode('utf-8')
< 
237c229
<                 'source': 'data:text/plain;charset=utf-8;base64,{}'.format(file_contents)
---
>                 'source': 'data:,{}'.format(quote(file_contents))
326c318
< 
---
>
```

I have only limited python skills ...

**Comment by ashcrow** [comment]
Ah I see. Sure I'll take a stab at it!

**Comment by lbohnsac** [comment]
The advantage is the possibility to drop binaries in the ignition file too

**Comment by lbohnsac** [comment]
two thumbs up! ;)

**Comment by lbohnsac** [comment]
Just realised that we need a proper mimetype for the output ... therefor we need a file mimetype detection too

**Comment by ashcrow** [comment]
In the PR we are discussing doing a slightly different pattern. PTAL.
