### ISSUE TITLE
Traceback while using the magic package

### ISSUE THREAD

**Issue by niteshnarayanlal** [ashcrow/filetranspiler#23]
[root@lab filetranspiler]# ./filetranspile -i ./test/ignition.json -f fake-root
Traceback (most recent call last):
  File "./filetranspile", line 367, in <module>
    main()
  File "./filetranspile", line 339, in main
    ignition_spec = spec_cls(ignition_cfg, args)
  File "./filetranspile", line 43, in __init__
    self.mimetype = magic.open(magic.MAGIC_MIME)
AttributeError: module 'magic' has no attribute 'open'
Exception ignored in: <bound method IgnitionSpec.__del__ of <__main__.SpecV2 object at 0x7f1401e93358>>
Traceback (most recent call last):
  File "./filetranspile", line 47, in __del__
    self.mimetype.close()
AttributeError: 'SpecV2' object has no attribute 'mimetype'

**Comment by niteshnarayanlal** [comment]
Already have python3-magic installed.

**Comment by ashcrow** [comment]
Thanks for the report! I'm looking into this.

**Comment by ashcrow** [comment]
>  AttributeError: module 'magic' has no attribute 'open'

Can you provide the version of `python3-magic` you are seeing this with. 

```
$ python3 -c 'import magic; print(magic.__file__); print(magic.open.__doc__)'
/usr/lib/python3.7/site-packages/magic.py

    Returns a magic object on success and None on failure.
    Flags argument as for setflags.
$  rpm -q --qf "%{VERSION}\n" python3-magic
5.37
$
```

Could it possibly be module naming collision [like this](https://stackoverflow.com/questions/25286176/how-to-use-python-magic-5-19-1)?

**Comment by niteshnarayanlal** [comment]
[root@virtlab1003 filetranspiler]#  python3 -c 'import magic; print(magic.__file__); print(magic.open.__doc__)'
/usr/local/lib/python3.6/site-packages/magic.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'magic' has no attribute 'open'

[root@lab filetranspiler]# rpm -q --qf "%{VERSION}\n" python3-magic
5.33

Somehow I didn't have the file-magic package installed. Installing that solved the issue, thanks for looking into it.

**Comment by ashcrow** [comment]
@niteshnarayanlal No worries! :smile:
