### ISSUE TITLE
ModuleNotFoundError: No module named 'magic'

### ISSUE THREAD

**Issue by jxadro** [ashcrow/filetranspiler#24]
Using both, python on the host or the container I get the same error: "ModuleNotFoundError: No module named 'magic'"

 podman run --rm -ti --volume `pwd`:/srv:z localhost/filetranspiler:latest -i bootstrap.ign -f bootstrap -o bootstrap0.ign
^Cls
Traceback (most recent call last):
  File "/usr/bin/filetranspile", line 10, in <module>
    import magic
ModuleNotFoundError: No module named 'magic'

**Comment by ashcrow** [comment]
Related: https://github.com/ashcrow/filetranspiler/issues/23

**Comment by ashcrow** [comment]
Thanks for the report. Verifying the Dockerfile. If the packages are not imported I'll updated it shortly.

**Comment by ashcrow** [comment]
https://github.com/ashcrow/filetranspiler/pull/25

**Comment by jxadro** [comment]
Thank you very much,

"dnf install -y python3-magic" made it work

**Comment by ashcrow** [comment]
@jxadro my pleasure! We'll merge the PR shortly so `master`'s container build is stable once more :+1:
